- name: Create directory and copy files on localhost
  hosts: localhost
  become: false  # No privilege escalation needed unless required
  tasks:
    - name: Create a directory
      ansible.builtin.file:
        path: ./example_directory
        state: directory
        mode: '0755'

    - name: Copy a file to the directory
      ansible.builtin.copy:
        src: /etc/ansible/ansible.cfg
        dest: ./example_directory/temp_ansible.cfg
        mode: '0644'
