---
- name: Configure webserver with Nginx and TLS
  hosts: webserver
  become: true
  gather_facts: false

  vars:
    tls_dir: /etc/nginx/sslfiles/
    key_file: nginx.key
    cert_file: nginx.crt
    conf_file: /etc/nginx/nginx.conf
    server_name: localhost
    nginx_sites_dirs:
      - /etc/nginx/sites-available
      - /etc/nginx/sites-enabled
      - /etc/nginx/sslfiles/

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

  tasks:
    - name: Ensure nginx is installed
      package:
        name: nginx
        update_cache: true
      notify: Restart nginx

    - name: Create directories for TLS certificates
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items: "{{ nginx_sites_dirs }}"
      notify: Restart nginx

    - name: Copy TLS files
      copy:
        src: "{{ item }}"
        dest: "{{ tls_dir }}"
        mode: '0600'
      loop:
        - "{{ key_file }}"
        - "{{ cert_file }}"
      notify: Restart nginx

    - name: Manage nginx config template
      template:
        src: nginx.conf.j2
        dest: "{{ conf_file }}"
        mode: '0644'
      notify: Restart nginx

    # - name: Enable configuration
    #   file:
    #     src: /etc/nginx/sites-available/default
    #     dest: /etc/nginx/sites-enabled/default
    #     state: link

    - name: Install home page
      template:
        src: index.xhtml.j2
        dest: /usr/share/nginx/html/index.xhtml
        mode: '0644'

    - name: Restart nginx
      meta: flush_handlers

    - name: Ensure firewalld is installed
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: Ensure firewalld is running and enabled
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Ensure HTTP and HTTPS services are allowed in the public zone
      ansible.builtin.firewalld:
        service: "{{ item }}"
        zone: public
        state: enabled
        permanent: true
      with_items:
        - http
        - https

    - name: Reload firewalld
      ansible.builtin.command:
        cmd: firewall-cmd --reload

    - name: "check the status of the remote server from localhost"
      uri:
        url: "http://localhost"
        validate_certs: false
        method: GET
        return_content: true
      register: out
      tags:
        - test
