# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/amazonlinux-2023"

  config.vm.box_check_update = false

  # Provision the VM with ifupdown installation
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y
    sudo yum install -y ifupdown
  SHELL

  # Uncomment the network type you want:
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.56.20"
  # config.vm.network "public_network"

  # Disable default synced folder
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end


end
